server:
  port: 8082

spring:
  application:
    name: driver-finder-service  # Name on Eureka
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Address of Eureka Server
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        amqp: DEBUG
    com:
      sercandorman:
        bookesh:
          driverfinder: DEBUG
